version: '3.9'
services:
  app:
    container_name: clava-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: db
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    tty: true

  db:
    container_name: clava-db
    image: mysql:8.0.29
    platform: linux/amd64
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - '3306:3306'
    volumes:
      - clava-db-data:/var/lib/mysql

volumes:
  clava-db-data:
